using Microsoft.AspNetCore.Mvc;
using WrightBrothersApi.Models;

namespace WrightBrothersApi.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class PlanesController : ControllerBase
    {
        private readonly ILogger<PlanesController> _logger;

        public PlanesController(ILogger<PlanesController> logger)
        {
            _logger = logger;
        }

        private static readonly List<Plane> Planes = new List<Plane>
        {
            new Plane
            {
                Id = 1,
                Name = "Wright Flyer",
                Year = 1903,
                Description = "The first successful heavier-than-air powered aircraft.",
                RangeInKm = 12,
                ImageUrl = "https://example.com/images/wright-flyer.jpg"
            },
            new Plane
            {
                Id = 2,
                Name = "Wright Flyer II",
                Year = 1904,
                Description = "A refinement of the original Flyer with better performance.",
                RangeInKm = 24,
                ImageUrl = "https://example.com/images/wright-flyer-ii.jpg"
            },
            new Plane
            {
                Id = 3,
                Name = "Wright Model A",
                Year = 1908,
                Description = "The first commercially successful airplane.",
                RangeInKm = 40,
                ImageUrl = "https://example.com/images/wright-model-a.jpg"
            },
            new Plane
            {
                Id = 4,
                Name = "Wright Model B",
                Year = 1910,
                Description = "The first airplane to be used for military purposes.",
                RangeInKm = 80,
                ImageUrl = "https://example.com/images/wright-model-b.jpg"
            }
        };

        [HttpGet]
        public ActionResult<List<Plane>> GetAll()
        {
            _logger.LogInformation("GET all ✈✈✈ NO PARAMS ✈✈✈");

            return Ok(Planes);
        }

        [HttpGet("{id}")]
        public ActionResult<Plane> GetById(int id)
        {
            var plane = Planes.Find(p => p.Id == id);

            if (plane == null)
            {
                return NotFound();
            }

            return Ok(plane);
        }

        // This attribute indicates that this method should be invoked for HTTP POST requests.
        [HttpPost]
        public ActionResult<Plane> Post(Plane plane)
        {
            // Check if a plane with the same name already exists in the Planes collection.
            // If it does, return a BadRequest response.
            if (Planes.Any(p => p.Name == plane.Name))
            {
                return BadRequest();
            }

            // If a plane with the same name does not exist, add the new plane to the Planes collection.
            Planes.Add(plane);

            // Log the information that a new plane has been added.
            _logger.LogInformation("POST ✈✈✈ {id} ✈✈✈", plane.Id);

            // Return a CreatedAtAction response, which includes the URI of the newly created plane.
            // The URI is generated by the GetById action.
            return CreatedAtAction(nameof(GetById), new { id = plane.Id }, plane);
        }
        
        [HttpPut("{id}")]
        public IActionResult Put(int id, Plane plane)
        {
            if (id != plane.Id)
            {
                return BadRequest();
            }

            var existingPlane = Planes.Find(p => p.Id == id);

            _logger.LogInformation("PUT ✈✈✈ {id} ✈✈✈", id);

            if (existingPlane == null)
            {
                return NotFound();
            }

            existingPlane.Name = plane.Name;
            existingPlane.Year = plane.Year;
            existingPlane.Description = plane.Description;
            existingPlane.RangeInKm = plane.RangeInKm;
            existingPlane.ImageUrl = plane.ImageUrl;

            return NoContent();
        }

        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            var plane = Planes.Find(p => p.Id == id);

            _logger.LogInformation("DELETE ✈✈✈ {id} ✈✈✈", id);

            if (plane == null)
            {
                return NotFound();
            }

            Planes.Remove(plane);

            return NoContent();
        }

        // Get my planes by year
        [HttpGet("year/{year}")]
        public ActionResult<List<Plane>> GetByYear(int year)
        {
            var planes = Planes.FindAll(p => p.Year == year);

            if (planes == null)
            {
                return NotFound();
            }

            return Ok(planes);
        }

        [HttpGet("count/{count}")]
        public ActionResult<List<Plane>> GetByCount(int count)
        {
            var planes = Planes.Take(count).ToList();

            if (planes == null)
            {
                return NotFound();
            }

            return Ok(planes);
        }


    }
}
